In [84]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder

In [85]:
df_train_labels = pd.read_csv('train_labels.csv')
df_train_sequences = pd.read_csv('train_sequences.csv')

In [86]:
df_train_labels.head()

         ID resname  resid     x_1        y_1     z_1
0  1SCL_A_1       G      1  13.760 -25.974001   0.102
1  1SCL_A_2       G      2   9.310 -29.638000   2.669
2  1SCL_A_3       G      3   5.529 -27.813000   5.878
3  1SCL_A_4       U      4   2.678 -24.900999   9.793
4  1SCL_A_5       G      5   1.827 -20.136000  11.793

In [87]:
df_train_sequences.head()

,target_id,sequence,temporal_cutoff,description,all_sequences
0,1SCL_A,GGGUGCUCAGUACGAGAGGAACCGCACCC,1995-01-26,"THE SARCIN-RICIN LOOP, A MODULAR RNA",>1SCL_1|Chain A|RNA SARCIN-RICIN LOOP|Rattus n...
1,1RNK_A,GGCGCAGUGGGCUAGCGCCACUCAAAAGGCCCAU,1995-02-27,THE STRUCTURE OF AN RNA PSEUDOKNOT THAT CAUSES...,>1RNK_1|Chain A|RNA PSEUDOKNOT|null\nGGCGCAGUG...
2,1RHT_A,GGGACUGACGAUCACGCAGUCUAU,1995-06-03,24-MER RNA HAIRPIN COAT PROTEIN BINDING SITE F...,>1RHT_1|Chain A|RNA (5'-R(P*GP*GP*GP*AP*CP*UP*...
3,1HLX_A,GGGAUAACUUCGGUUGUCCC,1995-09-15,P1 HELIX NUCLEIC ACIDS (DNA/RNA) RIBONUCLEIC ACID,>1HLX_1|Chain A|RNA (5'-R(*GP*GP*GP*AP*UP*AP*A...
4,1HMH_E,GGCGACCCUGAUGAGGCCGAAAGGCCGAAACCGU,1995-12-07,THREE-DIMENSIONAL STRUCTURE OF A HAMMERHEAD RI...,">1HMH_1|Chains A, C, E|HAMMERHEAD RIBOZYME-RNA..."

In [88]:
def one_hot_encode(seq):
    mapping = dict(zip("ACGU", range(4)))    
    seq2 = [mapping[i] for i in seq]
    return np.eye(4, dtype=int)[seq2]

In [89]:
df_train_labels[(df_train_labels['resname'].str.contains('-')) | (df_train_labels['resname'].str.contains('X'))]

                 ID resname  resid         x_1         y_1         z_1
87426     6WB1_C_53       -     53  146.863998  162.598007  114.521004
87427     6WB1_C_54       -     54  148.063995  168.145004  113.511002
94043   6Y0C_IN1_15       -     15  255.529999  194.612000  232.932999
94044   6Y0C_IN1_16       -     16  254.729996  200.151001  233.839005
113186     7SLP_R_1       X      1         NaN         NaN         NaN
130032    8H6E_4A_1       X      1         NaN         NaN         NaN

In [90]:
x = df_train_sequences[df_train_sequences['target_id'].str.contains('7SLP_R')]

In [91]:
x['description'].iloc[0]

'Cryo-EM structure of 7SK core RNP with linear RNA'

In [92]:
x['sequence'].iloc[0]

'XGAUGUGAGGGCGACUUCGGUCCUCCCUCACCGCUCCAUGUGCGAAAUGAGGCGCUGCAUGUGGCAGUCUGCCUUUCUUUU'

# Remove Invalid rows

In [94]:
df_train_labels = df_train_labels[~(df_train_labels['resname'].str.contains('-')) & ~(df_train_labels['resname'].str.contains('X'))]
df_train_labels.head()

         ID resname  resid     x_1        y_1     z_1
0  1SCL_A_1       G      1  13.760 -25.974001   0.102
1  1SCL_A_2       G      2   9.310 -29.638000   2.669
2  1SCL_A_3       G      3   5.529 -27.813000   5.878
3  1SCL_A_4       U      4   2.678 -24.900999   9.793
4  1SCL_A_5       G      5   1.827 -20.136000  11.793

In [95]:
df_train_labels.to_csv('new_train_labels.csv')

In [96]:
df_train_sequences = df_train_sequences[~(df_train_sequences['sequence'].str.contains('-')) & ~(df_train_sequences['sequence'].str.contains('X'))]
df_train_sequences.head()

,target_id,sequence,temporal_cutoff,description,all_sequences
0,1SCL_A,GGGUGCUCAGUACGAGAGGAACCGCACCC,1995-01-26,"THE SARCIN-RICIN LOOP, A MODULAR RNA",>1SCL_1|Chain A|RNA SARCIN-RICIN LOOP|Rattus n...
1,1RNK_A,GGCGCAGUGGGCUAGCGCCACUCAAAAGGCCCAU,1995-02-27,THE STRUCTURE OF AN RNA PSEUDOKNOT THAT CAUSES...,>1RNK_1|Chain A|RNA PSEUDOKNOT|null\nGGCGCAGUG...
2,1RHT_A,GGGACUGACGAUCACGCAGUCUAU,1995-06-03,24-MER RNA HAIRPIN COAT PROTEIN BINDING SITE F...,>1RHT_1|Chain A|RNA (5'-R(P*GP*GP*GP*AP*CP*UP*...
3,1HLX_A,GGGAUAACUUCGGUUGUCCC,1995-09-15,P1 HELIX NUCLEIC ACIDS (DNA/RNA) RIBONUCLEIC ACID,>1HLX_1|Chain A|RNA (5'-R(*GP*GP*GP*AP*UP*AP*A...
4,1HMH_E,GGCGACCCUGAUGAGGCCGAAAGGCCGAAACCGU,1995-12-07,THREE-DIMENSIONAL STRUCTURE OF A HAMMERHEAD RI...,">1HMH_1|Chains A, C, E|HAMMERHEAD RIBOZYME-RNA..."

In [97]:
df_train_sequences.to_csv('new_train_sequences.csv')

# Try OHE with clean data

In [54]:
df_train_labels['ohe'] = df_train_labels['resname'].apply(one_hot_encode)
df_train_labels.head()

Empty DataFrame
Columns: [ID, resname, resid, x_1, y_1, z_1, ohe]
Index: []